version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: note-app
      IMAGE_TAG: v1
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
            echo "export IMAGE_NAME=${IMAGE_NAME}" >> $BASH_ENV
            echo "export IMAGE_TAG=${IMAGE_TAG}" >> $BASH_ENV
      - run:
          name: List Docker Images
          command: |
            docker images

  publish-latest:
    environment:
      IMAGE_NAME: note-app
      IMAGE_TAG: v1
      USER_DOCKER: long1100
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /workspace
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "Start pushing"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag $IMAGE_NAME:$IMAGE_TAG $USER_DOCKER/$IMAGE_NAME:$IMAGE_TAG
            docker push $USER_DOCKER/$IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2.1
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main
