version: 2.1
orbs:
  node: circleci/node@5.1.0

workflows:
  node-tests:
    jobs:
      - node/test:
          override:
            - run:
                name: Lint
                command: npm run lint
                 
      # - run:
      #     name: Lint
      #     command: npm run lint
